#!/bin/bash

cat <<DELIM
[repo]
url     = http://ubik-repo.herokuapp.com:80
base    = 
branch  = public

[system]
# Uncomment to overwrite system info
# arch      = x86_64
# dist      = DEBIAN
# vers      = 6

[proxy]
# Http proxy: localhost:8888
http_proxy  = 
https_proxy =

# Http auth: user:password
http_auth   =
https_auth  =
# Timeout: default = 10
timeout     = 10

[logger]
# Log levels
#   - INFO      (1)
#   - ERROR     (2)
#   - DEBUG     (3)
level = 3

[packages]
pkg_blacklist   = "first second third"
control_methods = 
# Backup configuration files under etc/
safe_conf       = True

[settings]
var_path        = /usr/local/Ubik/var/lib
log_file        = /usr/local/Ubik/var/ubik.log
cache           = /usr/local/Ubik/var/lib/packages
packages        = /usr/local/Ubik

[webui]
users_file      = /usr/local/Ubik/etc/ubik.users
DELIM