#!/usr/bin/env python
# coding: utf-8
import sys

try:
    import flask
    from gevent.pywsgi import WSGIServer
    from geventwebsocket.handler import WebSocketHandler
except ImportError as err:
    print("Error: you need to install gevent dependencie (pip install flask gevent gevent-websocket)")
    print("Trackback: %s" % err)
    sys.exit(1)

from ubik.web import ubik_web
from ubik.web import logger

if __name__ == '__main__':
    try:
        http_server = WSGIServer(('',5000), ubik_web, handler_class=WebSocketHandler)
        http_server.serve_forever()
    except KeyboardInterrupt:
        logger.save()
        print('Stopping.')
        sys.exit(1)
